mod TypeNamespace {
    #[activatable]
    #[activatable(ITypeNameFactory)]
    class TypeName : ITypeName;

    // #[exclusive(TypeName)]
    // interface ITypeNameFactory {
    //     fn Create(&self) -> TypeName;
    //     fn CreateWithInt32(&self, value: i32) -> TypeName;
    // }

    interface ITypeName {
        fn GetValue(&self) -> u32;
    }

    mod Nested {

    }
}
