#![winrt] // optional, since the winrt dialect is the default

use Windows::Foundation::Metadata::{Activatable, ExclusiveTo};

mod TypeNamespace {
    #[Activatable(1)]
    #[Activatable(ITypeNameFactory, 1)]
    class TypeName : ITypeName;

    #[ExclusiveTo(TypeName)]
    interface ITypeNameFactory {
        fn CreateWithInt32(&self, value: i32) -> TypeName;
    }

    #[ExclusiveTo(TypeName)]
    interface ITypeName {
        fn GetValue(&self) -> i32;
    }
}
